behaviors:
  CourseAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 16384
      learning_rate: 3.0e-4
      beta: 5.0e-3            # entropy regularization
      epsilon: 0.2            # PPO clip
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 3.0e6
    time_horizon: 128
    summary_freq: 5000
    checkpoint_interval: 200000
